spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chiragmoorthy18/configuration-data-for-spring-microservices
          search-paths: SmartFood
server:
  port: 8762