eureka:
  client:
    service-url:
      defaultZone: http://172.18.3.44:8761/eureka
#server:
#  port: 8041
  
  
spring:
  h2:
    console:
      enabled: true
  application:
    name: customer-preference
  datasource:
#    password: sa
#    username: sa
#    url: jdbc:h2:mem:testdb
    password: mysql
    username: root
    url: jdbc:mysql://localhost:3306/spartans
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=sa
server:
  port: 8041
#spring.application.name=UserPreference
#spring.datasource.url=jdbc:mysql://remotemysql.com:3306/NfKf9WG8tS
#spring.datasource.username=NfKf9WG8tS
#spring.datasource.password=EjmCvI170M


#user= NfKf9WG8tS
#db =NfKf9WG8tS
#pass = EjmCvI170M
#Server: remotemysql.com
  